name: Deploy base workflow
on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
        description: 'The npm workspace name of the tenant you want to deploy.'
    secrets:
      ANDELA_ID_SECRET:
        required: false
        description: 'Optional: Andela Id Connection Client Secret.'
jobs:
  deploy-auth0-tenant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the changes
        uses: actions/checkout@v2
      - name: Deploy Changes
        env:
          ANDELA_ID_SECRET: ${{secrets.ANDELA_ID_SECRET}}
          GOOGLE_ANDELA_CLIENT_SECRET: ${{secrets.GOOGLE_ANDELA_CLIENT_SECRET}}
        run: |
          bash ./echo-env.sh

